### ISSUE TITLE
many JSONs need to use the localhost url instead of synbiohub.org

### ISSUE THREAD

**Issue by qwest123987** [SynBioHub/synbiohub3#488] opened 2023-07-27 13:15 UTC
some of the links in the new Synbiohub will redirect you to synbiohub.org/whateverYouAreLookingFor instead of localhost:7777/whateverYouAreLookingFor, which is an issue because some of the parts will then not be found. This issue can be fixed by getting the graph prefix and change it to the frontend URL in the UseRegistries file

**Comment by cjmyers** [comment] 2023-07-27 17:33
In URLs on front-end pages, the database prefix should be swapped with the instanceURL

web-of-registries can also be used

**Comment by danielfang97** [comment] 2023-09-18 19:50
Moved to SBH 2.1 milestone. Should be mostly working. Need to check for SBH 2.1 that the web of registries is doing the correct check.

**Comment by danielfang97** [comment] 2023-10-13 19:06
Duplicate of issue #520. Closed this one for now, and moved other one to 2.1

**Closed by danielfang97** 2023-10-13 19:06 UTC
Labels: frontend, viewing interface
