### ISSUE TITLE
Remove public enabled option is not taking effect

### ISSUE THREAD

**Issue by cjmyers** [SynBioHub/synbiohub3#791] opened 2024-11-04 18:30 UTC
When changing remove public enabled on the theme, configuration is saved but the behavior is not changed

**Comment by danielfang97** [comment] 2024-11-14 23:12
Duplicate of #701. Is assigned to Bianca

**Closed by danielfang97** 2024-11-14 23:12 UTC
Labels: bug

**Comment by cjmyers** [comment] 2024-11-14 23:49
Note that this is a SynBioHub1 issue actually, since it does not work with SBH1 either
